language: java
jdk:
- openjdk8
branches:
  except:
  - "/master-v0\\.1.*/"
install: true
before_script:
- chmod +x ./travis.sh
script:
- "./travis.sh"
before_deploy:
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- export GIT_TAG=$TRAVIS_BRANCH-v0.1.$TRAVIS_BUILD_NUMBER
- git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
- git push https://$GITHUB_TOKEN@github.com/hemantsonu20/jwt-cracker --tags
deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file: target/jwt-cracker-0.0.1-SNAPSHOT.jar
  skip_cleanup: true
  on:
    tags: false
    branch: master
after_deploy:
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- git checkout $TRAVIS_BRANCH
- git add docs/apidocs/* && git status
- git commit -m "[skip ci] adding javadocs travis build:$TRAVIS_BUILD_NUMBER"
- git push https://$GITHUB_TOKEN@github.com/hemantsonu20/jwt-cracker $TRAVIS_BRANCH
addons:
  sonarcloud:
    organization: hemantsonu20-github
    token:
      secure: "$SONAR_TOKEN"
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
notifications:
  email:
    recipients:
    - hemantsonu20@gmail.com
    on_success: change
    on_failure: always
env:
  global:
  - secure: sr/MHME/l8spn91+3wCmEVMtFSIeLHuw984BfHwi3teKdd+X9IAG5FSIoAVR/Dg40J8JANoXvd6FTtWgXWqk4KVHAt6ylEG5J5X2Cj5plSi8Y6j9lsIlVFlUYiCkC3Sl0TLY2jg6/LoKkoE7n8M+dg6rEcRetGmzrMH200JOqVqXRN9duw8HyrWM+ZCVICARB7J2byTblOw1O0NrX5kSwo++kZVkGCWyEbkuvPui5atDVJVHAN/xp2FqJh4EwCH6NIssf9JK/Jp6HmwChEd0IygvuIrn5DXGEx/4M8eNeJHK9jbK1w6xyrHt80B/SoG7TQeycdmGvZz30NQxIR0XLqRjmhXoJ1FQ3IMM1hNKsNBI9J6dXMTgCs6G+ShsQMjMhjgIZbT50dzwr+vGZs/G9Lq1yqxbfiLnMi0mjZyec664KcN7UF2bGDd+4tdeX3HTxMRH47shmv15ZwBMIwITMjFTRGjBJJXzx0ItcfJds4FQwE4rpZzzn8vswcV8ezatO2OXz3tTbPjr366av2tqpYeZY3FzeWF7GiRDacI+2C1Pxjn5bDpxSqO9d4beiL1GcfQXOXp/3y9WrrMCbQOwI9n6NHq4N+vNqh33Pq0sudyaMZ5hSpTQZaXUEMQ9BKDPUi7MOBxA+p6x8wX1iV/5z/Ccer0hPqA/6NQNGl/gs5M=
  - secure: cF1VLpJyzyjiqiMqz2wrEt8ME1IzHu+7TLtO2nzbqgTIAanlQe2L1w4jwXFi650vdC6GUbmo+vYUI/RELVyA24kWWeJ23p60PxihCNPa5jYZECcAz318zXy+foVV1zIT/QYyDWjnAhqXk3v7/G504x7pRnqTSzTmeN8beGfjbIsTcwHvpjB1E6uiBqBmugYz7grsSPiy4oL1wnqKq7ry8zveTHXa9VkyB9cni3+C71k1e63v8JYFIAlYvusf7cQmnjSLZkezojyzoP5yswZvhGqitLU5H5WfdRb6dpN+/0RkUVZ507fIL/jkKdqfZ3EMhhQ3Q5H74cwy1Ps/qDvBvCRD1m9iJ6D8x93JXanhI7MEWVlA3PMdgYUxf7Ak9W6GVjiSXhs32DEyEhA80QDjKNqdxznHMf/IixV6w3V5SPmUJYDZT2OlMPyHk0HR5YLQCPVMpqhH67oIMuXvXMwQPVJk22rs4UiovsgENleolqPF++is3RNapkG2nPIFy67gnNaAB6PY+EXonw8TIBgjrE8L1x6+5/gGwkq5xahPnf5DAXGOneLBYtnXkaF6A5RUHiZ7XGhjzkceRnIzfgBx1g4EsWFMNpNKGDZ4qeP47T06/TKiPR1t+0MZsqj6zfqZ3OKRzBT0rVwxL0rOGAoFQPoOkJqNPj9MhKaXsRsflTY=
