language: java
jdk: 
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install 
  - mvn sonar:sonar -Dsonar.github.oauth=$GITHUB_AUTH -Dsonar.analysis.mode=preview -Dsonar.github.repository=hemantsonu20/jwt-tracker -Dsonar.github.pullRequest=$TRAVIS_PULL_REQUEST
  - mvn org.sonarsource.scanner.maven:sonar-maven-plugin:3.2:sonar
notifications:
  email
    - hemantsonu20@gmail.com
addons:
  sonarqube:
    token:
      secure: $SONAR_TOKEN
#branches:
#  only:
#    - master
