language: java
jdk: 
  - openjdk8

branches:
  except:
    - /master-v0\.1.*/
  
script:
  - ./travis.sh
#  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install 
#  - mvn sonar:sonar
#  - mvn org.sonarsource.scanner.maven:sonar-maven-plugin:3.2:sonar

before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$TRAVIS_BRANCH-v0.1.$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push https://$GITHUB_TOKEN@github.com/hemantsonu20/jwt-cracker --tags
  
  # Commit docs folder
  - git add docs/apidocs/*
  - git commit -m "[skip ci] adding javadocs travis build:$TRAVIS_BUILD_NUMBER"
  - git push https://$GITHUB_TOKEN@github.com/hemantsonu20/jwt-cracker $TRAVIS_BRANCH

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: target/jwt-cracker-0.0.1-SNAPSHOT.jar
  skip_cleanup: true
  on:
    tags: false
    branch: master

notifications:
  email
    - hemantsonu20@gmail.com
addons:
  sonarcloud:
    organization: "hemantsonu20-github"
    token:
      secure: $SONAR_TOKEN
      
before_install:
  - chmod +x ./travis.sh
