language: java
jdk: 
  - oraclejdk8
script: 
  - mvn clean package sonar:sonar
notifications:
  email
    - hemantsonu20@gmail.com
addons:
  sonarqube:
    token:
      secure: $SONAR_TOKEN