language: java
jdk: 
  - openjdk8

branches:
  except:
    - /master-v0\.1.*/
  
script:
  - ./travis.sh

before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$TRAVIS_BRANCH-v0.1.$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push https://$GITHUB_TOKEN@github.com/hemantsonu20/jwt-cracker --tags

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: target/jwt-cracker-0.0.1-SNAPSHOT.jar
  skip_cleanup: true
  on:
    tags: false
    branch: master
    
after_deploy:
  # Commit docs folder
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - git checkout $TRAVIS_BRANCH
  - git add docs/apidocs/* && git status
  - git commit -m "[skip ci] adding javadocs travis build:$TRAVIS_BUILD_NUMBER"
  - git push https://$GITHUB_TOKEN@github.com/hemantsonu20/jwt-cracker $TRAVIS_BRANCH

notifications:
  email
    - hemantsonu20@gmail.com
addons:
  sonarcloud:
    organization: "hemantsonu20-github"
    token:
      secure: $SONAR_TOKEN
      
before_install:
  - chmod +x ./travis.sh
  
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    
